############################################## 端口以及编码配置 #########################################
server:
  # 端口
  port: 9999
  tomcat:
    uri-encoding: UTF-8
  servlet:
    # 配置请求编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 开启雅停机，默认IMMEDIATE是立即关机
  shutdown: graceful
spring:
  application:
    name: school-ms
  lifecycle:
    # 设置缓冲期，最大等待时间
    timeout-per-shutdown-phase: 30s
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      # 允许多文件上传
      enabled: true
      # 上传的总文件最大值
      max-file-size: 10MB
      # 上传单个文件的最大值
      max-request-size: 20MB
  ############################################## 配置数据源 ################################################
  datasource:
    # 数据库驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库URL
    # serverTimezone=GMT%2B8 (北京时间 == 东八区时间) 之前UTC 差了8小时 （暂改为东8）
    url: jdbc:mysql://school-ms-dev:3306/school-ms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # 数据库连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 5
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 15
      # 控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 连接池名称
      pool-name: MyHikariCP
      # connection在连接池中的存活时间默认30分钟
      max-lifetime: 1800000
      connection-timeout: 30000
      # 等待来自池的连接的最大毫秒数,默认 30000
    initialization-mode: always
    # 在初始化数据库时，遇到错误是否继续，默认false(不继续)
    continue-on-error: false
  ########################################### Thymeleaf相关配置 #######################################################
  thymeleaf:
    # 关闭 Thymeleaf 的缓存开发过程中无需重启
    cache: false
    # 模板模式为HTML5
    mode: LEGACYHTML5
    # 设置thymeleaf页面的后缀
    suffix: .html
    # 设置thymeleaf页面的编码
    encoding: UTF-8
    # 设置thymeleaf页面的存储路径
    prefix: classpath:/templates/
    # Content-Type配置
    servlet:
      content-type: text/html
    # 检查模版位置是否存在，默认为 true
    check-template-location: true
    # 检查模版是否存在，默认为 true
    check-template: true
  resources:
    # 静态资源存储路径
    static-locations: classpath:/templates/,classpath:/static/
    chain:
      strategy:
        content:
          # 是否开启内容版本策略，默认为false
          enabled: true
          # 指定要应用的版本的路径，多个以逗号分隔，默认为:[/**]
          paths: /**
  ########################################### Redis相关配置 #######################################################
  redis:
    # redis服务器地址
    host: school-ms-dev
    # redis服务器连接端口
    port: 6379
    # redis默认有16个分片，默认使用0号分片
    database: 0
    # 连接超时时间（毫秒）
    timeout: 2000
    # redis密码
    # password: 123456
    # 配置文件中添加 lettuce.pool 相关配置，则会使用到lettuce连接池
    lettuce:
      pool:
        # 连接池中最小连接
        min-idle: 10
        # 连接池最大连接数
        max-idle: 10
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 3000

######################################mybatis-plus 相关配置##########################################################
mybatis-plus:
  # xml扫描路径， 表示Mapper文件存放的位置，当Mapper文件跟对应的Mapper接口处于同一位置的时候可以不用指定该属性的值
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体类扫描路径， 多个package用逗号或者分号分隔
  type-aliases-package: com.george.school.**.entity
  #枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
  type-enums-package: com.george.school.**.enums
  global-config:
    # 是否开启 LOGO
    banner: false
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)",ID_WORKER_STR:"全局唯一ID (字符串类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER_STR
      # 表名、是否使用下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # 原生配置
  configuration:
    # 使用驼峰命名法转换字段
    map-underscore-to-camel-case: true
    # 使全局的映射器启用或禁用缓存。
    cache-enabled: true
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazy-loading-enabled: false
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multiple-result-sets-enabled: true
##########################################pageHelper相关配置#####################################################
pagehelper:
  # 分页合理化参数，默认值为false,
  # 该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # 方言属性
  helper-dialect: mysql
  # 自动分页的配置，依据的是入参，如果参数中有pageNum，pageSize分页参数，则会自动分页,默认false
  support-methods-arguments: true
  # count参数为countSql所得
  params: count=countSql
  row-bounds-with-count: true
  # 默认count查询关闭
  defaultCount: false
########################################## logback日志配置 #####################################################
logging:
  # 使用的logback文件
  config: classpath:logback/logback-dev.xml
  file:
    # 生成的日志文件路径
    path: F:\workspace\school-ms\logs
########################################## actuator服务监控 ##############################################
management:
  endpoint:
    # 允许actuator关机
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
############################################# shiro配置（自定义） #################################################
shiro:
  # session 超时时间，单位为秒
  sessionTimeout: 3600
  # rememberMe cookie有效时长，单位为秒
  cookieTimeout: 864000
  # 免认证的路径配置，如静态资源等
  anonUrl: /index/login,/assets/**,/layui/**,/vue/**,/actuator/**,/v3/api-docs,/swagger-ui/**,/swagger-resources/**,/api/image/captcha,/api/login
  # 登录 url
  loginUrl: /index/login
  # 首页 url
  successUrl: /index/home
  # 登出 url
  logoutUrl: /api/logout
  # 未授权跳转 url
  unauthorizedUrl: /index/unauthorized
  # rememberMe cookie 加密的密钥
  encryptKey: george_shiro_key
############################################# 其它自定义配置 #################################################
config:
  # 项目启动后是否使用系统默认浏览器打开登录页，默认开启
  autoOpenBrowser: true
  # Excel单次导入最大数据量，如 300个数据一次commit
  maxBatchInsertNum: 300
  # 验证码有效时间，单位秒
  codeTime: 120
  # 验证码图片格式，png
  codeType: png
  # 验证码图片宽度，px
  codeWidth: 120
  # 验证码图片高度，px
  codeHeight: 40
  # 验证码位数
  codeLength: 4
  # 验证码类型：1. 数字+字母；2. 纯数字；3. 纯字母
  codeCharType: 2
  # 文件服务器ip
  fileServerAddr: http://school-ms-dev:80
  # 用户头像上传路径
  headImagePath: /home/data/nginx/html/images
  # 用户头像访问前缀
  headUrlPrefix: /images