############################################## 多环境-通用配置(默认配置) #########################################
# 默认使用配置
spring:
  profiles:
    active: ${spring.profiles.active}
    # 配置文件的环境配置
    #（方案一：直接修改值为 dev 或 prod。 如：active: dev）
    # 方案二： 在idea中配置 (Run/Debug Configurations ---> Configuration --->) Active profiles 为 dev 或 prod

